# Generated by Django 5.1 on 2024-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_logrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrequests',
            name='success',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
