# Generated by Django 5.1 on 2024-08-17 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(default='', max_length=100)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('ALTERNATE', 'Alternate')], default='', max_length=100)),
                ('date_of_transaction', models.DateField(auto_now_add=True)),
                ('units', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
